# Generated by Django 5.2.15 on 2026-08-24 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('pro_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Застосовується, якщо у варіанта не задана ручна ціна.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Знижка для косметологів, %')),
                ('pro_min_order_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мінімальне замовлення для косметологів, грн')),
                ('pro_delivery_note_uk', models.TextField(blank=True, verbose_name='Умови доставки для косметологів (укр)')),
                ('pro_delivery_note_ru', models.TextField(blank=True, verbose_name='Умови доставки для косметологів (рос)')),
                ('retail_delivery_note_uk', models.TextField(blank=True, verbose_name='Умови доставки роздріб (укр)')),
                ('retail_delivery_note_ru', models.TextField(blank=True, verbose_name='Умови доставки роздріб (рос)')),
                ('free_delivery_from_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Безкоштовна доставка від, грн')),
                ('free_delivery_from_pro_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Безкоштовна доставка для косметологів від, грн')),
            ],
            options={
                'verbose_name': 'Ціни та умови',
                'verbose_name_plural': 'Ціни та умови',
            },
        ),
    ]
