# Generated by Django 5.2.15 on 2026-08-24 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='retail_markup_percent',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Використовується, щоб автоматично порахувати роздрібну ціну варіанта, якщо її залишили порожньою. Заповнену вручну ціну не змінює.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Націнка на роздріб від закупівельної, %'),
        ),
    ]
