# Generated by Django 5.2.15 on 2026-08-24 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricingsettings_retail_markup_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingsettings',
            name='pro_discount_percent',
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='pro_markup_percent',
            field=models.DecimalField(decimal_places=2, default=40, help_text='Ціна для косметологів = закупівельна + ця націнка.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Націнка для косметологів, %'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='rounding_step',
            field=models.CharField(choices=[('0.01', 'До копійки'), ('1.00', 'До гривні'), ('5.00', 'До 5 грн'), ('10.00', 'До 10 грн')], default='1.00', max_length=8, verbose_name='Округлення цін'),
        ),
        migrations.AlterField(
            model_name='pricingsettings',
            name='retail_markup_percent',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Роздрібна ціна = закупівельна + ця націнка.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Націнка роздріб, %'),
        ),
    ]
