# Generated by Django 5.2.15 on 2026-09-16 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_usage'),
        ('pricing', '0003_remove_pricingsettings_pro_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingsettings',
            options={'verbose_name': 'Налаштування цін', 'verbose_name_plural': 'Налаштування цін'},
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='global_sale_ends_at',
            field=models.DateTimeField(blank=True, help_text='Порожньо — без обмеження з кінця.', null=True, verbose_name='Кінець глобальної акції'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='global_sale_exclude_brands',
            field=models.ManyToManyField(blank=True, help_text='На ці бренди глобальна акція не діє (лишається персональна sale / роздріб).', related_name='+', to='catalog.brand', verbose_name='Виключити бренди'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='global_sale_exclude_products',
            field=models.ManyToManyField(blank=True, help_text='На ці товари глобальна акція не діє.', related_name='+', to='catalog.product', verbose_name='Виключити товари'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='global_sale_is_active',
            field=models.BooleanField(default=False, help_text='Знижка % на весь асортимент для гостей і звичайних клієнтів. Перебиває персональну акційну ціну варіанта. Косметологи не підпадають.', verbose_name='Глобальна акція увімкнена'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='global_sale_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Наприклад 20 = мінус 20% від роздрібної. 0 — без знижки.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Глобальна знижка, %'),
        ),
        migrations.AddField(
            model_name='pricingsettings',
            name='global_sale_starts_at',
            field=models.DateTimeField(blank=True, help_text='Порожньо — без обмеження з початку.', null=True, verbose_name='Початок глобальної акції'),
        ),
    ]
