# Generated by Django 5.2.15 on 2026-09-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_global_sale_and_price_source_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsettings',
            name='global_sale_is_active',
            field=models.BooleanField(default=False, help_text='Знижка % на весь асортимент для гостей і звичайних клієнтів. Перебиває персональну знижку % на варіанті. Косметологи не підпадають.', verbose_name='Глобальна акція увімкнена'),
        ),
    ]
