# Generated by Django 5.2.15 on 2026-08-24 09:12

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Телефон')),
                ('client_type', models.CharField(choices=[('regular', 'Звичайний клієнт'), ('pending_cosmo', 'Заявка косметолога'), ('cosmetologist', 'Косметолог')], db_index=True, default='regular', help_text='Змінюється лише адміністратором.', max_length=16, verbose_name='Тип клієнта')),
                ('client_type_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Статус змінено')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CosmetologistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('full_name', models.CharField(max_length=160, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('workplace', models.CharField(blank=True, max_length=255, verbose_name='Місце роботи')),
                ('document', models.FileField(blank=True, upload_to='cosmetologist/', verbose_name='Документ')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('approved', 'Схвалена'), ('rejected', 'Відхилена')], db_index=True, default='new', max_length=16, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Нотатка менеджера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetologist_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Заявка косметолога',
                'verbose_name_plural': 'Заявки косметологів',
                'ordering': ['-created_at'],
            },
        ),
    ]
