# Generated by Django 5.2.15 on 2026-08-24 11:03

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetologistrequest',
            name='document',
            field=models.FileField(blank=True, help_text='PDF або зображення до 5 МБ.', upload_to='cosmetologist/', validators=[apps.accounts.validators.validate_cosmetologist_document], verbose_name='Документ'),
        ),
    ]
