# Generated by Django 5.2.15 on 2026-08-24 09:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Програма увімкнена')),
                ('earn_points_per_uah', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='0.05 = 5 балів за кожні 100 грн.', max_digits=6, verbose_name='Балів за 1 грн')),
                ('redeem_uah_per_point', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Грн за 1 бал')),
                ('max_redeem_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Максимум списання, % від суми')),
                ('earn_for_pro', models.BooleanField(default=False, verbose_name='Нараховувати косметологам')),
            ],
            options={
                'verbose_name': 'Програма лояльності',
                'verbose_name_plural': 'Програма лояльності',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс балів')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Бонусний рахунок',
                'verbose_name_plural': 'Бонусні рахунки',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('kind', models.CharField(choices=[('earn', 'Нарахування'), ('redeem', 'Списання'), ('manual', 'Ручна операція')], max_length=16, verbose_name='Тип')),
                ('points', models.IntegerField(help_text='Плюс — нарахування, мінус — списання.', verbose_name='Бали')),
                ('balance_after', models.IntegerField(default=0, verbose_name='Баланс після')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount', verbose_name='Рахунок')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='commerce.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Бонусна операція',
                'verbose_name_plural': 'Бонусні операції',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'kind'), name='loyalty_unique_order_kind')],
            },
        ),
    ]
