# Generated by Django 5.2.15 on 2026-08-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltysettings',
            name='earn_hold_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Бали за покупку стають доступні до списання через стільки днів.', verbose_name='Днів до списання нарахованих балів'),
        ),
    ]
