# Generated by Django 5.2.15 on 2026-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (рос)')),
                ('subtitle_uk', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (укр)')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок (рос)')),
                ('image', models.ImageField(blank=True, upload_to='banners/', verbose_name='Зображення (десктоп)')),
                ('image_mobile', models.ImageField(blank=True, upload_to='banners/', verbose_name='Зображення (мобільне)')),
                ('button_text_uk', models.CharField(blank=True, max_length=60, verbose_name='Кнопка (укр)')),
                ('button_text_ru', models.CharField(blank=True, max_length=60, verbose_name='Кнопка (рос)')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='Посилання кнопки')),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (укр)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (рос)')),
                ('seo_description_uk', models.TextField(blank=True, verbose_name='SEO Description (укр)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO Description (рос)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL')),
                ('title_uk', models.CharField(max_length=255, verbose_name='Заголовок (укр)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (рос)')),
                ('body_uk', models.TextField(blank=True, verbose_name='Текст (укр)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Текст (рос)')),
                ('body_pro_uk', models.TextField(blank=True, verbose_name='Текст для косметологів (укр)')),
                ('body_pro_ru', models.TextField(blank=True, verbose_name='Текст для косметологів (рос)')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('site_name', models.CharField(default='SVbeauty', max_length=120, verbose_name='Назва сайту')),
                ('logo', models.ImageField(blank=True, upload_to='brand/', verbose_name='Логотип')),
                ('accent_color', models.CharField(default='#20847C', max_length=7, verbose_name='Акцентний колір (HEX)')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('manager_email', models.EmailField(blank=True, max_length=254, verbose_name='Email менеджера (чат, замовлення)')),
                ('viber', models.CharField(blank=True, max_length=255, verbose_name='Viber')),
                ('telegram', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=255, verbose_name='WhatsApp')),
                ('instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('promo_is_active', models.BooleanField(default=False, verbose_name='Показувати промо-смугу')),
                ('promo_text_uk', models.CharField(blank=True, max_length=255, verbose_name='Промо-текст (укр)')),
                ('promo_text_ru', models.CharField(blank=True, max_length=255, verbose_name='Промо-текст (рос)')),
                ('bank_recipient', models.CharField(blank=True, max_length=255, verbose_name='Отримувач')),
                ('bank_tax_id', models.CharField(blank=True, max_length=32, verbose_name='ІПН / ЄДРПОУ')),
                ('bank_iban', models.CharField(blank=True, max_length=64, verbose_name='IBAN')),
                ('bank_name', models.CharField(blank=True, max_length=160, verbose_name='Банк')),
                ('bank_purpose_template', models.CharField(blank=True, default='Оплата замовлення {order_number}', help_text='Доступний плейсхолдер {order_number}.', max_length=255, verbose_name='Призначення платежу')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
