# Generated by Django 5.2.15 on 2026-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='Графік роботи (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_uk',
            field=models.CharField(blank=True, max_length=120, verbose_name='Графік роботи (укр)'),
        ),
    ]
