# Generated by Django 5.2.15 on 2026-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sitesettings_work_hours_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Співвідношення 21:9. Рекомендовано 1680×720 або 1920×823 px, JPG/WebP.', upload_to='banners/', verbose_name='Зображення (десктоп)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Співвідношення 3:4. Рекомендовано 900×1200 px, JPG/WebP. Показується до 599 px.', upload_to='banners/', verbose_name='Зображення (мобільне)'),
        ),
    ]
