# Generated by Django 5.2.15 on 2026-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_banner_image_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_ru',
            field=models.CharField(blank=True, default='В каталог', max_length=60, verbose_name='Hero без банерів — кнопка (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_uk',
            field=models.CharField(blank=True, default='До каталогу', max_length=60, verbose_name='Hero без банерів — кнопка (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_ru',
            field=models.CharField(blank=True, default='Пилинги, сыворотки, кремы и SPF для домашнего и салонного применения.', max_length=300, verbose_name='Hero без банерів — підзаголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_uk',
            field=models.CharField(blank=True, default='Пілінги, сироватки, креми та SPF для домашнього і салонного застосування.', max_length=300, verbose_name='Hero без банерів — підзаголовок (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='Профессиональный уход за кожей', max_length=255, verbose_name='Hero без банерів — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_uk',
            field=models.CharField(blank=True, default='Професійний догляд за шкірою', max_length=255, verbose_name='Hero без банерів — заголовок (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.CharField(blank=True, default='Профессиональная косметика для домашнего и салонного ухода.', max_length=300, verbose_name='Meta / OG опис (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_uk',
            field=models.CharField(blank=True, default='Професійна косметика для домашнього та салонного догляду.', max_length=300, verbose_name='Meta / OG опис (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_button_ru',
            field=models.CharField(blank=True, default='Подать заявку', max_length=60, verbose_name='Блок косметологам — кнопка (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_button_uk',
            field=models.CharField(blank=True, default='Подати заявку', max_length=60, verbose_name='Блок косметологам — кнопка (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_text_ru',
            field=models.CharField(blank=True, default='Получите профессиональные цены и отдельные условия доставки. Отправьте заявку — менеджер подтвердит статус.', max_length=400, verbose_name='Блок косметологам — текст (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_text_uk',
            field=models.CharField(blank=True, default='Отримайте професійні ціни та окремі умови доставки. Надішліть заявку — менеджер підтвердить статус.', max_length=400, verbose_name='Блок косметологам — текст (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_title_ru',
            field=models.CharField(blank=True, default='Вы косметолог?', max_length=120, verbose_name='Блок косметологам — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_title_uk',
            field=models.CharField(blank=True, default='Ви косметолог?', max_length=120, verbose_name='Блок косметологам — заголовок (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_ru',
            field=models.CharField(blank=True, default='Профессиональная косметика для домашнего и салонного ухода.', max_length=255, verbose_name='Слоган у футері (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_uk',
            field=models.CharField(blank=True, default='Професійна косметика для домашнього та салонного догляду.', max_length=255, verbose_name='Слоган у футері (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp1_text_ru',
            field=models.CharField(blank=True, default='Работаем напрямую с производителем.', max_length=255, verbose_name='USP 1 — текст (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp1_text_uk',
            field=models.CharField(blank=True, default='Працюємо напряму з виробником.', max_length=255, verbose_name='USP 1 — текст (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp1_title_ru',
            field=models.CharField(blank=True, default='Оригинальная продукция', max_length=120, verbose_name='USP 1 — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp1_title_uk',
            field=models.CharField(blank=True, default='Оригінальна продукція', max_length=120, verbose_name='USP 1 — заголовок (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp2_text_ru',
            field=models.CharField(blank=True, default='Отделения и почтоматы по всей Украине.', max_length=255, verbose_name='USP 2 — текст (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp2_text_uk',
            field=models.CharField(blank=True, default='Відділення та поштомати по всій Україні.', max_length=255, verbose_name='USP 2 — текст (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp2_title_ru',
            field=models.CharField(blank=True, default='Доставка Новой Почтой', max_length=120, verbose_name='USP 2 — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp2_title_uk',
            field=models.CharField(blank=True, default='Доставка Новою Поштою', max_length=120, verbose_name='USP 2 — заголовок (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp3_text_ru',
            field=models.CharField(blank=True, default='Накапливайте баллы и оплачивайте ими покупки.', max_length=255, verbose_name='USP 3 — текст (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp3_text_uk',
            field=models.CharField(blank=True, default='Накопичуйте бали та оплачуйте ними покупки.', max_length=255, verbose_name='USP 3 — текст (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp3_title_ru',
            field=models.CharField(blank=True, default='Бонусная программа', max_length=120, verbose_name='USP 3 — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp3_title_uk',
            field=models.CharField(blank=True, default='Бонусна програма', max_length=120, verbose_name='USP 3 — заголовок (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp4_text_ru',
            field=models.CharField(blank=True, default='Поможем подобрать уход в чате.', max_length=255, verbose_name='USP 4 — текст (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp4_text_uk',
            field=models.CharField(blank=True, default='Допоможемо підібрати догляд у чаті.', max_length=255, verbose_name='USP 4 — текст (укр)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp4_title_ru',
            field=models.CharField(blank=True, default='Консультация', max_length=120, verbose_name='USP 4 — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='usp4_title_uk',
            field=models.CharField(blank=True, default='Консультація', max_length=120, verbose_name='USP 4 — заголовок (укр)'),
        ),
    ]
