# Generated by Django 5.2.15 on 2026-08-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings_home_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#1A1A1A', max_length=7, verbose_name='Акцентний колір (HEX)'),
        ),
    ]
