# Generated by Django 5.2.15 on 2026-08-31 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_sitesettings_tiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_color',
            field=models.CharField(default='#111111', help_text='Фон кнопки. Формат #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір кнопки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Текст на кнопці. Формат #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту кнопки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Заголовок і підзаголовок. Формат #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту'),
        ),
    ]
