# Generated by Django 5.2.15 on 2026-08-31 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_banner_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_bg_color',
            field=models.CharField(default='#1A1A1A', help_text='Видно без фото або під градієнтом поверх фото. #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Блок косметологам — колір фону'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_button_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Блок косметологам — колір кнопки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_button_text_color',
            field=models.CharField(default='#111111', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Блок косметологам — колір тексту кнопки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_image',
            field=models.ImageField(blank=True, help_text='Фон на весь блок. Рекомендовано 1600×560, JPG/WebP.', upload_to='brand/', verbose_name='Блок косметологам — зображення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_image_mobile',
            field=models.ImageField(blank=True, help_text='Опційно. Якщо порожньо — показується десктопне. Рекомендовано 900×700.', upload_to='brand/', verbose_name='Блок косметологам — зображення (мобільне)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pro_cta_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Блок косметологам — колір тексту'),
        ),
    ]
