# Generated by Django 5.2.15 on 2026-09-16 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_banner_button_url_localize'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='accent_hover_color',
            field=models.CharField(default='#186F68', help_text='Hover для primary-кнопок. Темніший відтінок акценту.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір кнопок при наведенні (HEX)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#20847C', help_text='Фон primary-кнопок (Купити, реквізити тощо). З логотипу: #20847C.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір кнопок / акцент (HEX)'),
        ),
    ]
