# Generated by Django 5.2.15 on 2026-09-16 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_accent_hover_brand_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_color',
            field=models.CharField(blank=True, default='', help_text='Порожньо — колір бренду (accent). Інакше #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text_color',
            field=models.CharField(blank=True, default='', help_text='Порожньо — білий текст на кнопці бренду. Інакше #RRGGBB.', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Колір тексту кнопки'),
        ),
    ]
