# Generated by Django 5.2.15 on 2026-08-24 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Сесія')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('converted', 'Оформлений'), ('abandoned', 'Покинутий')], default='active', max_length=16, verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер')),
                ('client_type', models.CharField(default='regular', max_length=16, verbose_name='Тип клієнта на момент покупки')),
                ('first_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_city', models.CharField(blank=True, max_length=160, verbose_name='Місто')),
                ('delivery_city_ref', models.CharField(blank=True, max_length=64, verbose_name='Ref міста')),
                ('delivery_branch', models.CharField(blank=True, max_length=255, verbose_name='Відділення')),
                ('delivery_branch_ref', models.CharField(blank=True, max_length=64, verbose_name='Ref відділення')),
                ('payment_method', models.CharField(choices=[('bank_details', 'Переказ на рахунок ФОП'), ('liqpay', 'Картка онлайн (LiqPay)')], default='bank_details', max_length=16, verbose_name='Оплата')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('awaiting_payment', 'Очікує оплати'), ('paid', 'Оплачено'), ('shipped', 'Відправлено'), ('done', 'Виконано'), ('canceled', 'Скасовано')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('subtotal_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума позицій')),
                ('loyalty_spent_points', models.PositiveIntegerField(default=0, verbose_name='Списано балів')),
                ('loyalty_discount_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Знижка балами, грн')),
                ('total_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='До сплати')),
                ('bank_details_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Реквізити')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар клієнта')),
                ('gdpr_accepted', models.BooleanField(default=False, verbose_name='Згода на обробку даних')),
                ('locale', models.CharField(default='uk', max_length=2, verbose_name='Мова')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product_name', models.CharField(max_length=255, verbose_name='Товар')),
                ('sku', models.CharField(max_length=64, verbose_name='Артикул')),
                ('volume', models.CharField(blank=True, max_length=32, verbose_name="Об'єм")),
                ('unit_price_uah', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('price_source', models.CharField(default='retail', max_length=10, verbose_name='Джерело ціни')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('line_total_uah', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Замовлення')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.variant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Було')),
                ('new_status', models.CharField(max_length=20, verbose_name='Стало')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто змінив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='commerce.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусу',
                'verbose_name_plural': 'Історія статусів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart', verbose_name='Кошик')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.variant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Позиція кошика',
                'verbose_name_plural': 'Позиції кошика',
                'constraints': [models.UniqueConstraint(fields=('cart', 'variant'), name='cart_unique_variant')],
            },
        ),
    ]
