# Generated by Django 5.2.15 on 2026-08-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_purchase_price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупівельна за одиницю'),
        ),
    ]
