# Generated by Django 5.2.15 on 2026-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_orderitem_unit_purchase_price_uah'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Вулиця, будинок, квартира для доставки таксі.', max_length=255, verbose_name='Адреса (таксі)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('pickup', 'Самовивіз'), ('taxi', 'Таксі')], db_index=True, default='nova_poshta', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Відділення / адреса'),
        ),
    ]
