# Generated by Django 5.2.15 on 2026-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_delivery_methods_pickup_taxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_recipient',
            field=models.BooleanField(default=False, verbose_name='Інший отримувач'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="Ім'я отримувача"),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Прізвище отримувача'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон отримувача'),
        ),
    ]
