# Generated by Django 5.2.15 on 2026-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_order_other_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_source',
            field=models.CharField(default='retail', max_length=16, verbose_name='Джерело ціни'),
        ),
    ]
