# Generated by Django 5.2.15 on 2026-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('np_api_key', models.CharField(blank=True, help_text='Без ключа працює тестовий довідник міст і відділень.', max_length=255, verbose_name='API-ключ Нової Пошти')),
                ('use_test_data', models.BooleanField(default=False, verbose_name='Примусово тестові дані')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставка',
            },
        ),
    ]
