# Generated by Django 5.2.15 on 2026-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingsettings',
            options={'verbose_name': 'Налаштування доставки', 'verbose_name_plural': 'Налаштування доставки'},
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='pickup_address_ru',
            field=models.CharField(blank=True, default='г. Киев, ул. Крещатик, 1', max_length=255, verbose_name='Адреса самовивозу (рос)'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='pickup_address_uk',
            field=models.CharField(blank=True, default='м. Київ, вул. Хрещатик, 1', max_length=255, verbose_name='Адреса самовивозу (укр)'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True, verbose_name='Самовивіз увімкнено'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='pickup_note_ru',
            field=models.CharField(blank=True, default='Заберите заказ после подтверждения менеджером.', max_length=255, verbose_name='Підказка самовивозу (рос)'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='pickup_note_uk',
            field=models.CharField(blank=True, default='Заберіть замовлення після підтвердження менеджером.', max_length=255, verbose_name='Підказка самовивозу (укр)'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='taxi_enabled',
            field=models.BooleanField(default=True, verbose_name='Таксі увімкнено'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='taxi_note_ru',
            field=models.CharField(blank=True, default='Стоимость такси согласует менеджер. Укажите адрес доставки.', max_length=255, verbose_name='Підказка таксі (рос)'),
        ),
        migrations.AddField(
            model_name='shippingsettings',
            name='taxi_note_uk',
            field=models.CharField(blank=True, default='Вартість таксі узгоджує менеджер. Вкажіть адресу доставки.', max_length=255, verbose_name='Підказка таксі (укр)'),
        ),
    ]
