# Generated by Django 5.2.15 on 2026-08-24 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (рос)')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (укр)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (рос)')),
                ('seo_description_uk', models.TextField(blank=True, verbose_name='SEO Description (укр)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO Description (рос)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('name_uk', models.CharField(max_length=120, verbose_name='Назва (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Назва (рос)')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Фото категорії')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (рос)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('seo_title_uk', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (укр)')),
                ('seo_title_ru', models.CharField(blank=True, max_length=255, verbose_name='SEO Title (рос)')),
                ('seo_description_uk', models.TextField(blank=True, verbose_name='SEO Description (укр)')),
                ('seo_description_ru', models.TextField(blank=True, verbose_name='SEO Description (рос)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('name_uk', models.CharField(max_length=255, verbose_name='Назва (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Назва (рос)')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='URL')),
                ('short_description_uk', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис (укр)')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис (рос)')),
                ('description_uk', models.TextField(blank=True, verbose_name='Опис (укр)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (рос)')),
                ('ingredients_uk', models.TextField(blank=True, verbose_name='Склад (укр)')),
                ('ingredients_ru', models.TextField(blank=True, verbose_name='Склад (рос)')),
                ('is_hit', models.BooleanField(db_index=True, default=False, verbose_name='Хіт продажу')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Новинка')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt_uk', models.CharField(blank=True, max_length=255, verbose_name='Alt (укр)')),
                ('alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt (рос)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
                'ordering': ['-is_main', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('volume', models.CharField(max_length=32, verbose_name="Об'єм")),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна роздрібна, грн')),
                ('price_pro_uah', models.DecimalField(blank=True, decimal_places=2, help_text='Порожньо — застосується глобальний відсоток знижки.', max_digits=10, null=True, verbose_name='Ціна для косметологів, грн')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': "Варіант (об'єм)",
                'verbose_name_plural': "Варіанти (об'єми)",
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='catalog_pro_is_acti_1a8de5_idx'),
        ),
    ]
