# Generated by Django 5.2.15 on 2026-08-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='purchase_price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Службове поле, на сайті не показується. Від нього рахуються інші ціни.', max_digits=10, null=True, verbose_name='Закупівельна ціна, грн'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Порожньо — порахується від закупівельної плюс націнка з розділу «Ціни та умови».', max_digits=10, null=True, verbose_name='Ціна роздрібна, грн'),
        ),
    ]
