# Generated by Django 5.2.15 on 2026-08-24 10:13

from django.db import migrations, models


def fill_missing_prices(apps, schema_editor):
    """Порожні ціни зі старої схеми переносимо в закупівельні, щоб поля стали NOT NULL."""
    Variant = apps.get_model('catalog', 'Variant')
    Variant.objects.filter(price_uah__isnull=True).update(price_uah=0)
    Variant.objects.filter(price_pro_uah__isnull=True).update(price_pro_uah=0)
    for variant in Variant.objects.filter(purchase_price_uah__isnull=True):
        variant.purchase_price_uah = variant.price_uah or 0
        variant.save(update_fields=['purchase_price_uah'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_variant_purchase_price_uah_alter_variant_price_uah'),
    ]

    operations = [
        migrations.RunPython(fill_missing_prices, migrations.RunPython.noop),
        migrations.AddField(
            model_name='variant',
            name='price_is_manual',
            field=models.BooleanField(default=False, help_text='Увімкніть, щоб автоперерахунок не перезаписував цю ціну.', verbose_name='Роздрібна ціна вручну'),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_pro_is_manual',
            field=models.BooleanField(default=False, help_text='Увімкніть, щоб автоперерахунок не перезаписував цю ціну.', verbose_name='Ціна косметолога вручну'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_pro_uah',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Порожньо — порахується автоматично від закупівельної плюс націнка.', max_digits=10, verbose_name='Ціна для косметологів, грн'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Порожньо — порахується автоматично від закупівельної плюс націнка.', max_digits=10, verbose_name='Роздрібна ціна, грн'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='purchase_price_uah',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Службове поле, на сайті не показується. Від нього рахуються інші ціни.', max_digits=10, verbose_name='Закупівельна ціна, грн'),
        ),
    ]
