# Generated by Django 5.2.15 on 2026-08-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_variant_price_is_manual_variant_price_pro_is_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('name_uk', models.CharField(max_length=120, verbose_name='Назва (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Назва (рос)')),
                ('slug', models.SlugField(max_length=140, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['group__sort_order', 'sort_order', 'name_uk'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показувати на сайті')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('slug', models.SlugField(choices=[('age', 'За віком'), ('skin_type', 'За типом шкіри'), ('skin_condition', 'За станом шкіри'), ('ingredient', 'Інгредієнти')], max_length=40, unique=True, verbose_name='Код')),
                ('name_uk', models.CharField(max_length=120, verbose_name='Назва (укр)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Назва (рос)')),
            ],
            options={
                'verbose_name': 'Група характеристик',
                'verbose_name_plural': 'Групи характеристик',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Вік, тип/стан шкіри, інгредієнти — з’являються у фільтрах каталогу.', related_name='products', to='catalog.productattribute', verbose_name='Характеристики для фільтрів'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.productattributegroup', verbose_name='Група'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='uniq_attr_group_slug'),
        ),
    ]
