# Generated by Django 5.2.15 on 2026-08-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_wishlist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attributes',
            new_name='filter_attrs',
        ),
    ]
