# Generated by Django 5.2.15 on 2026-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_product_attributes_to_filter_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sale_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Акція до'),
        ),
        migrations.AddField(
            model_name='variant',
            name='sale_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Знижка для гостей і звичайних клієнтів. Косметологи бачать pro-ціну без акції. 0 — без акції. Потрібні дати початку й кінця.', max_digits=5, verbose_name='Акція, % від роздрібної'),
        ),
        migrations.AddField(
            model_name='variant',
            name='sale_starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Акція з'),
        ),
    ]
