# Generated by Django 5.2.15 on 2026-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_variant_sale_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='sale_ends_at',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sale_percent',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sale_starts_at',
        ),
        migrations.AddField(
            model_name='variant',
            name='sale_price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Для гостей і звичайних клієнтів. Показується, якщо більша за 0 і менша за роздрібну. Косметологи бачать pro-ціну без акції. 0 — без акції.', max_digits=10, verbose_name='Акційна ціна, грн'),
        ),
    ]
