# Generated by Django 5.2.15 on 2026-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_ingredients_to_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_promo_text_ru',
            field=models.TextField(blank=True, verbose_name='Банер подарунка — текст (рос)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_promo_text_uk',
            field=models.TextField(blank=True, help_text='Короткий текст на банері. Порожньо — банер не показується.', verbose_name='Банер подарунка — текст (укр)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_promo_title_ru',
            field=models.CharField(blank=True, default='Пробник в подарок', max_length=120, verbose_name='Банер подарунка — заголовок (рос)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_promo_title_uk',
            field=models.CharField(blank=True, default='Пробник у подарунок', max_length=120, verbose_name='Банер подарунка — заголовок (укр)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_promo_tooltip_ru',
            field=models.TextField(blank=True, verbose_name='Банер подарунка — підказка «i» (рос)'),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_promo_tooltip_uk',
            field=models.TextField(blank=True, help_text='Детальний опис акції у спливаючій підказці біля іконки «i».', verbose_name='Банер подарунка — підказка «i» (укр)'),
        ),
    ]
