# Generated by Django 5.2.15 on 2026-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_gift_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='Ставиться лише якщо користувач має оплачене замовлення з цим товаром.', verbose_name='Покупка підтверджена'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Нові відгуки чекають модерації в адмінці.', verbose_name='Опубліковано'),
        ),
    ]
