# Generated by Django 5.2.15 on 2026-09-15 11:44

import apps.core.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_review_moderation_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', validators=[apps.core.utils.images.validate_image], verbose_name='Фото категорії'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[apps.core.utils.images.validate_image], verbose_name='Зображення'),
        ),
    ]
