# Generated by Django 5.2.15 on 2026-09-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_category_productimage_image_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_ru',
            field=models.TextField(blank=True, verbose_name='Спосіб застосування (рос)'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_uk',
            field=models.TextField(blank=True, help_text='Текст застосування на сторінці товару (вкладка «Спосіб застосування»).', verbose_name='Спосіб застосування (укр)'),
        ),
    ]
