# Generated by Django 5.2.15 on 2026-08-24 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='Ключ сесії')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрито')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Діалог',
                'verbose_name_plural': 'Діалоги',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('author', models.CharField(choices=[('customer', 'Клієнт'), ('manager', 'Менеджер')], max_length=10, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='Діалог')),
            ],
            options={
                'verbose_name': 'Повідомлення',
                'verbose_name_plural': 'Повідомлення',
                'ordering': ['created_at'],
            },
        ),
    ]
