# Generated by Django 5.2.15 on 2026-09-16 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Хто з персоналу надіслав повідомлення. Потрібно, щоб видаляти лише свої.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages_authored', to=settings.AUTH_USER_MODEL, verbose_name='Автор (менеджер)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Видалено о'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Видалено'),
        ),
    ]
