# Generated by Django 5.2.15 on 2026-09-24 13:07

import apps.chat.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Повідомлення'),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(max_length=240, storage=apps.chat.storage.private_chat_storage, upload_to=apps.chat.storage.chat_upload_to, verbose_name='Файл')),
                ('original_name', models.CharField(max_length=180, verbose_name='Назва')),
                ('kind', models.CharField(choices=[('image', 'Зображення'), ('pdf', 'PDF')], max_length=8, verbose_name='Тип')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Розмір, байти')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage', verbose_name='Повідомлення')),
            ],
            options={
                'verbose_name': 'Вкладення',
                'verbose_name_plural': 'Вкладення',
                'ordering': ['created_at'],
            },
        ),
    ]
